service: slack-send-app

provider:
    name: aws
    runtime: nodejs8.10
    stage: dev
    region: us-east-1
    memorySize: 128
    versionFunctions: false
    cfLogs: true
    iamRoleStatements:
        - Effect: "Allow"
          Action:
              - "dynamodb:*"
          Resource: "*"
    environment:
        DDB_TOKENS: slack-send-server-${opt:stage, self:provider.stage}-v0.0-tokens
        DDB_MESSAGES: ${self:service}-${opt:stage, self:provider.stage}-v0.0-messages
package:
    exclude:
        - .npmignore
        - fixtures/**
        - .git/**
functions:
    schedule:
        handler: handler.scheduled_event
        description: Handle scheduled event
        timeout: 30
        events:
            - schedule:
                name: ${self:service}-${opt:stage, self:provider.stage}-every-5-mins
                description: Every 5 minutes
                rate: rate(5 minutes)
                enabled: true
            - http:
                path: slack/send/run
                method: get
                private: false
    command:
        handler: handler.slack_command
        description: Handle slash commands from Slack
        timeout: 30
        events:
            - http:
                path: slack/send/command
                method: post
                private: false
            - schedule:
                rate: rate(5 minutes)
                description: keeps lambda warm
                enabled: true
                input:
                  inputpath: "/slack/send/command"
    actions:
        handler: handler.slack_actions
        description: Handle interactive message actions from Slack
        timeout: 30
        events:
            - http:
                path: slack/send/actions
                method: post
                private: false
            - schedule:
                rate: rate(5 minutes)
                description: keeps lambda warm
                enabled: true
                input:
                  inputpath: "/slack/send/actions"
    options:
        handler: handler.slack_options
        description: Handle interactive message options from Slack
        timeout: 30
        events:
            - http:
                path: slack/send/options
                method: post
                private: false
    events:
        handler: handler.slack_events
        description: Handle events from Slack
        timeout: 30
        events:
            - http:
                path: slack/send/events
                method: post
                private: false
resources:
    Resources:
        TableScheduledMessages:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:provider.environment.DDB_MESSAGES}
                AttributeDefinitions:
                    - AttributeName: ymd
                      AttributeType: S
                    - AttributeName: id
                      AttributeType: S
                    - AttributeName: date_id
                      AttributeType: S
                    - AttributeName: team_id
                      AttributeType: S
                    - AttributeName: user_id
                      AttributeType: S
                KeySchema:
                    - AttributeName: ymd
                      KeyType: HASH
                    - AttributeName: date_id
                      KeyType: RANGE
                ProvisionedThroughput:
                    ReadCapacityUnits: 20
                    WriteCapacityUnits: 5
                GlobalSecondaryIndexes:
                    - IndexName: team_user_index
                      KeySchema:
                          - AttributeName: team_id
                            KeyType: HASH
                          - AttributeName: user_id
                            KeyType: RANGE
                      Projection:
                          ProjectionType: ALL
                      ProvisionedThroughput:
                          ReadCapacityUnits: 20
                          WriteCapacityUnits: 0
                    - IndexName: team_id_index
                      KeySchema:
                          - AttributeName: team_id
                            KeyType: HASH
                          - AttributeName: id
                            KeyType: RANGE
                      Projection:
                          ProjectionType: ALL
                      ProvisionedThroughput:
                          ReadCapacityUnits: 20
                          WriteCapacityUnits: 0
        ScheduleLogGroup:
            Properties:
                RetentionInDays: "7"
        CommandLogGroup:
            Properties:
                RetentionInDays: "7"
        ActionsLogGroup:
            Properties:
                RetentionInDays: "7"
        OptionsLogGroup:
            Properties:
                RetentionInDays: "7"
        EventsLogGroup:
            Properties:
                RetentionInDays: "7"
