service: slack-send-messages-app

provider:
    name: aws
    runtime: nodejs6.10
    stage: dev
    region: us-east-1
    memorySize: 128
    versionFunctions: false
    cfLogs: true
    iamRoleStatements:
        - Effect: "Allow"
          Action:
              - "dynamodb:*"
          Resource: "*"
    environment:
        DDB_TOKENS: ${self:service}-${opt:stage, self:provider.stage}-v0.0-tokens
        DDB_SCH_MSG: ${self:service}-${opt:stage, self:provider.stage}-v0.0-sch_messages
package:
    exclude:
        - .npmignore
        - fixtures/**
        - .git/**
functions:
    schedule:
        handler: handler.scheduled_event
        description: Handle scheduled event
        timeout: 30
        events:
            - schedule:
                name: ${self:service}-${opt:stage, self:provider.stage}-every-5-mins
                description: Every 5 minutes
                rate: rate(5 minutes)
                enabled: true
            - http:
                path: slack/send/run
                method: get
                private: false
    redirect:
        handler: handler.slack_redirect
        description: Handle OAuth redirect for Slack
        timeout: 30
        events:
            - http:
                path: slack/send/redirect
                method: get
                private: false
    command:
        handler: handler.slack_command
        description: Handle slash commands from Slack
        timeout: 30
        events:
            - http:
                path: slack/send/command
                method: post
                private: false
    event:
        handler: handler.slack_event
        description: Handle events from Slack
        timeout: 30
        events:
            - http:
                path: slack/send/event
                method: post
                private: false
resources:
    Resources:
        TableTokens:
            Type: AWS::DynamoDB::Table 
            Properties:
                TableName: ${self:provider.environment.DDB_TOKENS}
                AttributeDefinitions:
                    - AttributeName: team_id
                      AttributeType: S
                    - AttributeName: channel_id
                      AttributeType: S
                KeySchema:
                    - AttributeName: team_id
                      KeyType: HASH
                    - AttributeName: channel_id
                      KeyType: RANGE
                ProvisionedThroughput:
                    ReadCapacityUnits: 20
                    WriteCapacityUnits: 20
        TableScheduledMessages:
            Type: AWS::DynamoDB::Table 
            Properties:
                TableName: ${self:provider.environment.DDB_SCH_MSG}
                AttributeDefinitions:
                    - AttributeName: ymd
                      AttributeType: S
                    - AttributeName: iso_date
                      AttributeType: S
                KeySchema:
                    - AttributeName: ymd
                      KeyType: HASH
                    - AttributeName: iso_date
                      KeyType: RANGE
                ProvisionedThroughput:
                    ReadCapacityUnits: 20
                    WriteCapacityUnits: 20
        ScheduleLogGroup:
            Properties:
                RetentionInDays: "7"
        RedirectLogGroup:
            Properties:
                RetentionInDays: "7"
        CommandLogGroup:
            Properties:
                RetentionInDays: "7"
        EventLogGroup:
            Properties:
                RetentionInDays: "7"
